import { CompanyData } from '../types';

export const downloadJSON = (data: CompanyData | CompanyData[]) => {
  const isArray = Array.isArray(data);
  const name = isArray ? `FinanceSource_Comparison_${data.length}_Companies` : `${data.company.ticker}_FinanceSource_Analysis`;
  
  const jsonString = `data:text/json;chatset=utf-8,${encodeURIComponent(
    JSON.stringify(data, null, 2)
  )}`;
  const link = document.createElement("a");
  link.href = jsonString;
  link.download = `${name}.json`;
  link.click();
};

export const generateMarkdown = (data: CompanyData): string => {
  const { company, profile, indices, analysis, ownership, pressure_levers } = data;
  const date = new Date().toLocaleDateString();

  return `
# FINANCE SOURCE ANALYSIS REPORT
**Target:** ${company.name} (${company.ticker})
**Date:** ${date}
**Sector:** ${company.sector}

---

## 1. EXECUTIVE SUMMARY
**ISC Score:** ${indices.ISC.toFixed(2)} / 10
**Dominant Control Mode:** ${indices.dominant_mode}
**Market Cap:** ${profile.market_cap}

**Description:**
${profile.description}

---

## 2. CONTROL INDICES
| Index | Score | Summary |
| :--- | :--- | :--- |
| **Formal Control (CF)** | ${indices.CF}/10 | ${analysis.formal_control.summary} |
| **Capital Control (CC)** | ${indices.CC}/10 | ${analysis.capital_control.summary} |
| **Market Constraint (CM)** | ${indices.CM}/10 | ${analysis.market_constraint.summary} |
| **Revenue Power (CR)** | ${indices.CR}/10 | ${analysis.revenue_power.summary} |
| **Productive Power (CP)** | ${indices.CP}/10 | ${analysis.productive_power.summary} |

---

## 3. OWNERSHIP
**Institutional:** ${ownership.institutional_percent}%
**Retail:** ${ownership.retail_percent}%
**Insiders:** ${ownership.insider_percent}%

**Top Shareholders:**
${ownership.top_holders.map(h => `- ${h.name} (${h.percent}%): ${h.family}`).join('\n')}

---
*Generated by Finance Source Intelligence Engine*
`;
};

export const generateComparisonMarkdown = (companies: CompanyData[]): string => {
    const date = new Date().toLocaleDateString();
    
    let md = `# FINANCE SOURCE COMPARISON REPORT\n**Date:** ${date}\n\n`;
    
    // Summary Table
    md += `| Ticker | Name | ISC Score | Dominant Mode | Market Cap |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;
    
    companies.forEach(c => {
        md += `| **${c.company.ticker}** | ${c.company.name} | ${c.indices.ISC.toFixed(2)} | ${c.indices.dominant_mode} | ${c.profile.market_cap} |\n`;
    });
    
    md += `\n---\n\n## DETAILED INDICES\n\n`;
    md += `| Ticker | CF | CC | CM | CR | CP |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- | :--- |\n`;
    
    companies.forEach(c => {
        md += `| **${c.company.ticker}** | ${c.indices.CF} | ${c.indices.CC} | ${c.indices.CM} | ${c.indices.CR} | ${c.indices.CP} |\n`;
    });
    
    return md;
};

export const downloadMarkdown = (data: CompanyData | CompanyData[]) => {
  let mdContent = "";
  let filename = "";

  if (Array.isArray(data)) {
      mdContent = generateComparisonMarkdown(data);
      filename = `FinanceSource_Comparison_${data.length}.md`;
  } else {
      mdContent = generateMarkdown(data);
      filename = `${data.company.ticker}_Analysis_Report.md`;
  }

  const element = document.createElement("a");
  const file = new Blob([mdContent], {type: 'text/markdown'});
  element.href = URL.createObjectURL(file);
  element.download = filename;
  document.body.appendChild(element); 
  element.click();
  document.body.removeChild(element);
};

export const downloadHTML = (data: CompanyData | CompanyData[]) => {
    const isArray = Array.isArray(data);
    const companies = isArray ? data : [data];
    const date = new Date().toLocaleDateString();

    // Cross ownership logic for HTML
    const allInvestors = new Set<string>();
    companies.forEach(c => c.ownership.top_holders.forEach(h => allInvestors.add(h.name)));
    const uniqueInvestors = Array.from(allInvestors).sort();

    const htmlContent = `
    <!DOCTYPE html>
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Finance Source Report - ${date}</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap');
            body { font-family: 'Inter', sans-serif; background-color: #ffffff; color: #0f172a; }
            .section { margin-bottom: 2rem; border: 1px solid #e2e8f0; border-radius: 0.5rem; padding: 1.5rem; }
            h1 { font-size: 2rem; font-weight: 700; color: #1e293b; margin-bottom: 0.5rem; }
            h2 { font-size: 1.5rem; font-weight: 600; color: #334155; margin-bottom: 1rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }
            table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
            th { text-align: left; padding: 0.75rem; background-color: #f1f5f9; border-bottom: 2px solid #e2e8f0; font-weight: 600; }
            td { padding: 0.75rem; border-bottom: 1px solid #e2e8f0; }
            .score-badge { display: inline-block; padding: 0.25rem 0.5rem; border-radius: 0.25rem; font-weight: bold; background-color: #e0e7ff; color: #4338ca; }
        </style>
    </head>
    <body class="p-8 max-w-5xl mx-auto">
        
        <header class="mb-8 border-b pb-4">
            <h1 class="text-3xl font-bold">Finance Source Rapport Analytique</h1>
            <p class="text-slate-500">Généré le ${date}</p>
        </header>

        ${isArray ? `
        <div class="section">
            <h2>Matrice d'Actionnariat Croisé</h2>
            <table>
                <thead>
                    <tr>
                        <th>Investisseur</th>
                        ${companies.map(c => `<th>${c.company.ticker}</th>`).join('')}
                    </tr>
                </thead>
                <tbody>
                    ${uniqueInvestors.map(inv => `
                        <tr>
                            <td class="font-medium">${inv}</td>
                            ${companies.map(c => {
                                const h = c.ownership.top_holders.find(x => x.name === inv);
                                return `<td>${h ? h.percent + '%' : '-'}</td>`;
                            }).join('')}
                        </tr>
                    `).join('')}
                </tbody>
            </table>
        </div>
        ` : ''}

        ${companies.map(c => `
            <div class="section break-inside-avoid">
                <div class="flex justify-between items-start mb-4">
                    <div>
                        <h2 class="!border-0 !mb-0 text-2xl">${c.company.name} (${c.company.ticker})</h2>
                        <div class="text-sm text-slate-500">${c.profile.market_cap} • ${c.company.sector}</div>
                    </div>
                    <div class="text-right">
                        <div class="text-sm text-slate-500 uppercase">Score ISC</div>
                        <div class="text-3xl font-bold text-indigo-600">${c.indices.ISC.toFixed(2)}</div>
                    </div>
                </div>

                <p class="mb-6 text-slate-700 italic">${c.profile.description}</p>

                <div class="grid grid-cols-2 gap-4 mb-6">
                    <div class="p-4 bg-slate-50 rounded border">
                        <h3 class="font-bold text-sm uppercase mb-2">Structure de Contrôle</h3>
                        <ul class="text-sm space-y-1">
                            <li><strong>Formel (CF):</strong> ${c.indices.CF}/10</li>
                            <li><strong>Capital (CC):</strong> ${c.indices.CC}/10</li>
                            <li><strong>Marché (CM):</strong> ${c.indices.CM}/10</li>
                            <li><strong>Revenus (CR):</strong> ${c.indices.CR}/10</li>
                            <li><strong>Productif (CP):</strong> ${c.indices.CP}/10</li>
                        </ul>
                    </div>
                    <div class="p-4 bg-slate-50 rounded border">
                         <h3 class="font-bold text-sm uppercase mb-2">Répartition Actionnariat</h3>
                         <ul class="text-sm space-y-1">
                            <li><strong>Institutionnels:</strong> ${c.ownership.institutional_percent}%</li>
                            <li><strong>Retail:</strong> ${c.ownership.retail_percent}%</li>
                            <li><strong>Insiders:</strong> ${c.ownership.insider_percent}%</li>
                         </ul>
                    </div>
                </div>

                <h3 class="font-bold text-sm uppercase mb-2">Top Actionnaires</h3>
                <table class="mb-4">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Famille</th>
                            <th class="text-right">%</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${c.ownership.top_holders.map(h => `
                            <tr>
                                <td>${h.name}</td>
                                <td><span class="text-xs bg-slate-100 px-2 py-1 rounded">${h.family}</span></td>
                                <td class="text-right font-mono">${h.percent}%</td>
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
                
                <div class="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded text-sm">
                    <strong>Risque Majeur:</strong> ${c.pressure_levers[0]?.force} (${c.pressure_levers[0]?.type}) - ${c.pressure_levers[0]?.notes}
                </div>
            </div>
        `).join('')}

        <footer class="mt-12 pt-6 border-t text-center text-sm text-slate-400">
            &copy; 2026 Finance Source Intelligence Engine
        </footer>

    </body>
    </html>
    `;

    const element = document.createElement("a");
    const file = new Blob([htmlContent], {type: 'text/html'});
    element.href = URL.createObjectURL(file);
    element.download = isArray ? `FinanceSource_Comparison_Export.html` : `${data.company.ticker}_Full_Report.html`;
    document.body.appendChild(element); 
    element.click();
    document.body.removeChild(element);
};